AWS_UPLOAD_BUCKET = "nayak-cloud-bucket"

AWS_UPLOAD_USERNAME = "nayak_cloud_user"

AWS_UPLOAD_GROUP = "nayak-cloud-group"

AWS_UPLOAD_REGION = 'us-west-2'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAZANEFFXSFMUOWA4E"

AWS_UPLOAD_SECRET_KEY = "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"
