# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
