# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='upload',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
