# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileitem_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='upload',
        ),
    ]
