# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20171019_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
